{
 "title": "Swingletree Metrics",
 "description": "Overview of Swingletree metrics",
 "tags": [
  "swingletree",
  "builds"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Processed Builds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "checkStatus.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "2" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select metric",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "sonarqube",
   "type": "singlestat",
   "description": "Builds blocked by sonarqube",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "timestamp",
       "id": "1",
       "meta": {},
       "pipelineVariables": [
        { "name": "source.", "pipelineAgg": "select metric" }
       ],
       "settings": {},
       "type": "count"
      }
     ],
     "query": "sender.keyword: \"sonarqube\" AND checkStatus.keyword: \"blocked\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "security/twistlock",
   "type": "singlestat",
   "description": "Builds blocked by security/twistlock",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 9 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "timestamp",
       "id": "1",
       "meta": {},
       "pipelineVariables": [
        { "name": "source.", "pipelineAgg": "select metric" }
       ],
       "settings": {},
       "type": "count"
      }
     ],
     "query": "sender.keyword: \"security/twistlock\" AND checkStatus.keyword: \"blocked\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "security/zap",
   "type": "singlestat",
   "description": "Builds blocked by security/zap",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 9 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select metric",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "pipelineVariables": [
        { "name": "source.", "pipelineAgg": "select metric" }
       ],
       "settings": {},
       "type": "count"
      }
     ],
     "query": "sender.keyword: \"security/zap\" AND checkStatus.keyword: \"blocked\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Last Builds",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 10 },
       "type": "raw_document"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Builds Processed",
   "type": "singlestat",
   "description": "Builds processed by Swingletree",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 15 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "timestamp",
       "id": "1",
       "meta": {},
       "pipelineVariables": [
        { "name": "source.", "pipelineAgg": "select metric" }
       ],
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  }
 ]
}