{
 "title": "Swingletree Builds",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "SonarQube reports",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:71",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:69",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "sender.keyword: \"sonarqube\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Nebula reports",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:71",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:69",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "sender.keyword: \"gradle/nebula\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Processed Reports",
   "type": "graph",
   "description": "Processed reports by kind (sender)",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total Processed Reports",
     "bucketAggs": [
      {
       "$$hashKey": "object:746",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:744",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "timestamp"
    },
    {
     "alias": "Sonarqube",
     "bucketAggs": [
      {
       "$$hashKey": "object:882",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:880", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sender.keyword: \"sonarqube\"",
     "timeField": "timestamp"
    },
    {
     "alias": "Twistlock",
     "bucketAggs": [
      {
       "$$hashKey": "object:900",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:898", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sender.keyword: \"security/twistlock\"",
     "timeField": "timestamp"
    },
    {
     "alias": "OWASP ZAP",
     "bucketAggs": [
      {
       "$$hashKey": "object:1045",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:1043", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sender.keyword: \"security/zap\"",
     "timeField": "timestamp"
    },
    {
     "alias": "Nebula",
     "bucketAggs": [
      {
       "$$hashKey": "object:389",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:387", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sender.keyword: \"gradle/nebula\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Twistlock reports",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "targets": [
    {
     "alias": "Total",
     "bucketAggs": [
      {
       "$$hashKey": "object:71",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:69",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "sender.keyword: \"security/twistlock\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "OWASP ZAP reports",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:71",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:69",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "sender.keyword: \"security/zap\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Processed reports",
   "type": "stat",
   "description": "Processed reports of any kind",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:71",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:69",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "master builds with issues",
   "type": "graph",
   "description": "master builds with issues by kind (sender)",
   "gridPos": { "h": 10, "w": 8, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "security/twistlock",
     "bucketAggs": [
      {
       "$$hashKey": "object:497",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:495", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source.branch.keyword: \"master\" AND sender.keyword: \"security/twistlock\" AND checkStatus.keyword: \"blocked\"",
     "timeField": "timestamp"
    },
    {
     "alias": "sonarqube",
     "bucketAggs": [
      {
       "$$hashKey": "object:520",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:518", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source.branch.keyword: \"master\" AND sender.keyword: \"sonarqube\" AND checkStatus.keyword: \"blocked\"",
     "timeField": "timestamp"
    },
    {
     "alias": "security/zap",
     "bucketAggs": [
      {
       "$$hashKey": "object:1177",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:1175", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source.branch.keyword: \"master\" AND sender.keyword: \"security/zap\" AND checkStatus.keyword: \"blocked\"",
     "timeField": "timestamp"
    },
    {
     "alias": "gradle/nebula",
     "bucketAggs": [
      {
       "$$hashKey": "object:455",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:453", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source.branch.keyword: \"master\" AND sender.keyword: \"gradle/nebula\" AND checkStatus.keyword: \"blocked\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "master builds with issues",
   "type": "table",
   "description": "master builds with reported issues need to be investigated.\n\nYou can use the data rows to define filters for the dashboard.",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 10 },
   "targets": [
    {
     "metrics": [
      {
       "$$hashKey": "object:1793",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 75 },
       "type": "raw_document"
      }
     ],
     "query": "source.branch.keyword: \"master\" AND checkStatus.keyword: \"blocked\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "master builds with issues",
   "type": "stat",
   "description": "Blocked master builds indicate that issues were found in the master branch.\n\nAny emerged issue should be investigated.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:71",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:69",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "source.branch.keyword: \"master\" AND checkStatus.keyword: \"blocked\"",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}