@startuml Swingletree flow
  GitHub --> CI : trigger build
  activate CI
  CI --> SonarQube: analysis data
  deactivate CI
  activate SonarQube
  SonarQube -> Swingletree : webhook event
  deactivate SonarQube
  Swingletree -> GitHub : update check run status
@enduml
